
name: nota_toko
description: Aplikasi Nota Toko Offline SQLite
publish_to: 'none'

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  sqflite: ^2.3.0
  path_provider: ^2.1.2
  image_picker: ^1.1.2
  esc_pos_bluetooth: ^0.5.0
  esc_pos_utils: ^0.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true

